Repository Felipe-Cavalca/predocs, pull requests merged in 2022-11, with the labels that each got.

#15 Criação de log das tabelas
  server/core/Banco.php
Labels: Aprimoramento

#18 editando readme.md do servidor
  server/README.md
Labels: Documentação, Aprimoramento

#24 Retirando vue js do sistema
  app/components/js/nav.js
  app/js/global/funcoes.js
  app/models/config/includes.json
  app/pages/index.html
Labels: Aprimoramento

#26 Adicionando favicon no sistema
  app/midia/global/favicon.ico
Labels: Aprimoramento

#28 Update README.md
  README.md
Labels: Documentação

#32 corrigindo erros no serviço
  server/core/Funcoes.php
Labels: Bug

#33 Melhora desempenho gets
  app/core/index.js
Labels: Aprimoramento
